variable "vpc_name" {}
variable "name" {}
variable "region" {}
variable "account_id" {}
variable "lambda_arn" {}
variable "resource_path_part" {}
variable "zone_domain" {}
variable "domain" {}
variable "certificate_domain" {}
variable "lambda_sha" {}
